NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
ACCOUNTS = [
    "GCNVDZIHGX473FEI7IXCUAEXUJ4BGCKEMHF36VYP5EMS7PX2QBLAMTLA"
]

[DOCUMENTATION]
ORG_NAME = "Montelibero Association"
ORG_URL = "https://mtla.me/"
#ORG_LOGO = "https://mtla.me/stellar-logo.png"
ORG_DESCRIPTION = "DAO related to Montelibero movement."
ORG_PHYSICAL_ADDRESS = "Montenegro"
ORG_OFFICIAL_EMAIL = "common@mtla.me"

[[CURRENCIES]]
code = "MTLAP"
issuer = "GCNVDZIHGX473FEI7IXCUAEXUJ4BGCKEMHF36VYP5EMS7PX2QBLAMTLA"
is_asset_anchored = false
desc = "The asset is membership confirmation for individuals."
#image = "https://mtla.me/stellar-logo-mtlap.png"
display_decimals = 0

[[CURRENCIES]]
code = "MTLAC"
issuer = "GCNVDZIHGX473FEI7IXCUAEXUJ4BGCKEMHF36VYP5EMS7PX2QBLAMTLA"
is_asset_anchored = false
desc = "The asset is membership confirmation for organizations."
#image = "https://mtla.me/stellar-logo-mtlap.png"
display_decimals = 0
